server.port=8080
spring.application.name=notifications-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/hayday
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.com.hayday=INFO
logging.level.org.springframework.data.mongodb=DEBUG
